# Generated by Django 4.2.16 on 2024-11-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tagline',
            field=models.CharField(default='Tagling', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
